export const AUTHORIZATION_FLOWS = {
    AUTHORIZATION_CODE: 'AUTHORIZATION_CODE',
    IMPLICIT: 'IMPLICIT',
    CLIENT_CREDENTIAL: 'CLIENT_CREDENTIAL',
};

export const BROWSER_TYPES = {
    INAPPBROWSER: 'InAppBrowser',
    SYSTEMBROWSER: 'SystemBrowser',
};
